Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.box_version = "20211001.0.0"
	config.vm.synced_folder "../", "/vagrant", id: "vagrant-root", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]
	config.vm.provision "shell", path: "./provision/script.sh"

	config.vm.hostname = "vm.localhost"
	config.vm.network "forwarded_port", guest: 80, host: 8080

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 2
	end
end